<?php
/**
 * 菜单配置文件
 */

return [
    [
        'type' => 'file',
        'name' => 'training',
        'title' => '在线培训',
        'icon' => 'fa fa-suitcase',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'sublist' => [
            [
                'type' => 'file',
                'name' => 'training/category',
                'title' => '培训分类',
                'icon' => 'fa fa-list',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'training/category/import',
                        'title' => '导入',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/category/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/category/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/category/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/category/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/category/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'training/course',
                'title' => '课程管理',
                'icon' => 'fa fa-youtube-play',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'training/course/import',
                        'title' => '导入',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/course/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/course/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/course/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/course/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/course/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'training/main',
                'title' => '培训管理',
                'icon' => 'fa fa-book',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'training/main/import',
                        'title' => '导入',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/main/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/main/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/main/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/main/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'training/main/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'training/index',
                'title' => '培训统计',
                'icon' => 'fa fa-bar-chart',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'training/index/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ]
                ],
            ],
            [
                'type' => 'file',
                'name' => 'training/config',
                'title' => '站点配置',
                'icon' => 'fa fa-gears',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'training/config/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ]
                ],
            ],
        ],
    ],
];