<?php

return [
    [
        'name' => 'sitename',
        'title' => '网站名称',
        'type' => 'string',
        'value' => '在线培训系统',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'cheat',
        'title' => '防作弊',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => '',
        'tip' => '开启后将屏蔽浏览器调试模式',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'outboard',
        'title' => '防挂机',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => '',
        'tip' => '开启后视频播放页面将监测鼠标事件，失去焦点将暂停播放',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'mobile',
        'title' => '禁止移动端',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => '',
        'tip' => '开启后将仅允许PC端浏览器访问',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'pastview',
        'title' => '过期后是否允许回看',
        'content' => [
            1 => '允许',
            0 => '不允许',
        ],
        'value' => '0',
        'rule' => '',
        'tip' => '培训过期后是否允许再次播放视频',
        'extend' => '',
    ],
    [
        'name' => 'uploadcycle',
        'title' => '上传周期',
        'type' => 'number',
        'value' => '2000',
        'rule' => 'range(100~10000)',
        'msg' => '学习进度上传周期',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'future_show',
        'title' => '显示“未开始”',
        'value' => '1',
        'content' => [
            '不显示',
            '显示',
        ],
        'tip' => '首页中是否显示“未开始”分组',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'past_show',
        'title' => '显示“已过期”',
        'value' => '1',
        'content' => [
            '不显示',
            '显示',
        ],
        'tip' => '首页中是否显示“已过期”分组',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/training/$',
            'index/main' => '/training/main/[:id]',
            'index/alert' => '/training/alert/[:msg]',
            'course/index' => '/training/course/[:main_id]/[:course_id]',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'main_open_type',
        'title' => '培训窗口打开方式',
        'value' => '1',
        'content' => [
            '新窗口',
            '本窗口跳转',
        ],
        'tip' => '前台培训页面窗口打开方式',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'select',
        'name' => 'datalimit',
        'title' => '后台数据限制',
        'value' => 'false',
        'content' => [
            'false' => '不启用',
            'personal' => '当前管理员',
            'auth' => '当前及下级管理员',
        ],
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
];
